<?php

namespace Database\Seeders;

use App\Models\Rental;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PricingTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pricing')->insert([
            //Arckezelések
            [
                'name' => 'Tisztító kezelés',
                'category' => 'Arckezelések',
                'duration' => '90-120 perc',
                'price' => 8500,
                'features' => 'letisztítás, peeling, arcmasszázs, gőzölés, tisztítás, nyugtató pakolás, befejező krém',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Váll tisztító kezelés',
                'category' => 'Arckezelések',
                'duration' => '70-100 perc',
                'price' => 7500, // Note: There are two prices listed, using the lower one
                'features' => 'letisztítás, peeling, gőzölés, tisztítás, nyugtató pakolás, befejező krém',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Hát tisztító kezelés',
                'category' => 'Arckezelések',
                'duration' => '70-100 perc',
                'price' => 9500, // Note: There are two prices listed, using the lower one
                'features' => 'letisztítás, peeling, gőzölés, tisztítás, nyugtató pakolás, befejező krém',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Tini kezelés',
                'category' => 'Arckezelések',
                'duration' => '60-90 perc',
                'price' => 7500,
                'features' => 'letisztítás, peeling, gőzölés, tisztítás, VIO, nyugtató pakolás, befejező krém',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Nagykezelés',
                'category' => 'Arckezelések',
                'duration' => '90-120 perc',
                'price' => 11500,
                'features' => 'letisztítás, peeling, arcmasszázs, gőzölés, tisztítás, ultrahangos hatóanyagbevitel, nyugtató pakolás, befejező krém',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Arcmasszázs hatóanyagos krémekkel',
                'category' => 'Arckezelések',
                'duration' => '60-75 perc',
                'price' => 6000,
                'features' => 'letisztítás, peeling, pakolás, arcmasszázs, befejezőkrém',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Dekoltázsamasszázs hatóanyagos krémekkel',
                'category' => 'Arckezelések',
                'duration' => '90-100 perc',
                'price' => 7000,
                'features' => 'letisztítás, peeling, pakolás, arc-és dekoltázsmasszázs, befejezőkrém',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Ultrahang speciális hatóanyagkoncentrátummal',
                'category' => 'Arckezelések',
                'duration' => null,
                'price' => 3000,
                'features' => 'Csak kezelés vagy masszázs mellé kérhető',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Aha savas hámlasztás ',
                'category' => 'Arckezelések',
                'duration' => null,
                'price' => 6000,
                'features' => 'letisztítás, Aha sav és Aha savas pakolás, tonizálás, nyugtatás, befejezőkrém',
                'other_features' => null,
                'rental_id' => Rental::all()
                    ->where('id', '=', 1)->first()->id,

            ],
            //Gépi kezelések
            [
                'name' => 'Hydroglow mélytisztítás',
                'category' => 'Gépi kezelések',
                'duration' => '80-100 perc',
                'price' => 12000,
                'features' => 'letisztítás, tonizálás, gőzölés, hidrodermabrázió 3 lépésben (hámlasztás, tisztítás, hidratálás), kézi tisztítás
és fertőtlenítés - amennyiben szükséges, hidegkalapács, búcsú krém',
                'other_features' => 'Mélytisztítás problémás, mitesszeres bőrre - fájdalommentesen',
                'rental_id' => null,
            ],
            [
                'name' => 'Hydroglow beauty',
                'category' => 'Gépi kezelések',
                'duration' => '90-120 perc',
                'price' => 14000,
                'features' => 'letisztítás, hidroabrázió, tonizálás, hidrodermabrázió 3 lépésben (hámlasztás, tisztítás, hidratálás),
hidegkalapács, ultrahang, oxigénposztoly',
                'other_features' => 'Személyre szabott tisztítás, hidratálás és táplálás',
                'rental_id' => null,
            ],
            [
                'name' => 'Hydroglow Anti-Age arc',
                'category' => 'Gépi kezelések',
                'duration' => '80-100 perc',
                'price' => 14500,
                'features' => 'letisztítás, hidroabrázió, tonizálás, ultrahang, masszázs, rádiófrekvencia, hidegvasaló, oxigénpisztoly',
                'other_features' => 'megereszkedett, fakó bőrre. Hidratálás, táplálás, feszesítés',
                'rental_id' => null,
            ],
            [
                'name' => 'Hydroglow anti-age arc + nyak',
                'category' => 'Gépi kezelések',
                'duration' => '~120perc',
                'price' => 16500,
                'features' => 'letisztítás, hidroabrázió, tonizálás, ultrahang, masszázs, rádiófrekvencia, hidegvasaló, oxigénpisztoly',
                'other_features' => 'megereszkedett, fakó bőrre. Hidratálás, táplálás, feszesítés',
                'rental_id' => null,
            ],
            [
                'name' => 'Hydroglow anti-age arc + nyak + dekoltázs',
                'category' => 'Gépi kezelések',
                'duration' => '~150perc',
                'price' => 18500,
                'features' => 'letisztítás, hidroabrázió, tonizálás, ultrahang, masszázs, rádiófrekvencia, hidegvasaló, oxigénpisztoly',
                'other_features' => 'megereszkedett, fakó bőrre. Hidratálás, táplálás, feszesítés',
                'rental_id' => null,
            ],
            [
                'name' => 'Rádiófrekvencia arc',
                'category' => 'Gépi kezelések',
                'duration' => '45-60 perc',
                'price' => 7000,
                'features' => '',
                'other_features' => null,
                'rental_id' => Rental::all()
                    ->where('id', '=', 2)->first()->id,
            ],
            [
                'name' => 'Rádiófrekvencia arc + nyak',
                'category' => 'Gépi kezelések',
                'duration' => '~75 perc',
                'price' => 8500,
                'features' => '',
                'other_features' => null,
                'rental_id' => Rental::all()
                    ->where('id', '=', 3)->first()->id,
            ],
            [
                'name' => 'Rádiófrekvencia arc + nyak + dekoltázs',
                'category' => 'Gépi kezelések',
                'duration' => '~90 perc',
                'price' => 10000,
                'features' => '',
                'other_features' => null,
                'rental_id' => Rental::all()
                    ->where('id', '=', 4)->first()->id,
            ],
            [
                'name' => 'Hydroglow Relax arc',
                'category' => 'Gépi kezelések',
                'duration' => '~80 perc',
                'price' => 9500,
                'features' => 'letisztítás, hidroabrázió, tonizálás, ultrahangos hatóanyagbevitel, 15 perces relaxáló masszázs, bőrnek
megfelelő arcpakolás, oxigénpisztoly',
                'other_features' => 'Mindenkinek, aki egy kis feltöltődésre vágyik - hidratálás, táplálás, relaxáció',
                'rental_id' => null,
            ],
            [
                'name' => 'Hydroglow relax arc + dekoltázs',
                'category' => 'Gépi kezelések',
                'duration' => '~100 perc',
                'price' => 11000,
                'features' => 'letisztítás, hidroabrázió, tonizálás, ultrahangos hatóanyagbevitel, 15 perces relaxáló masszázs, bőrnek
megfelelő arcpakolás, oxigénpisztoly',
                'other_features' => 'Mindenkinek, aki egy kis feltöltődésre vágyik - hidratálás, táplálás, relaxáció',
                'rental_id' => null,
            ],
            [
                'name' => 'Hydroglow Sensitive arc',
                'category' => 'Gépi kezelések',
                'duration' => '~60 perc',
                'price' => 7500,
                'features' => 'letisztítás, hidroabrázió, tonizálás, kímélő arcmasszázs, hidegkalapács, bőrnyugtató / gyulladáscsökkentő
arcpakolás, oxigénpisztoly',
                'other_features' => 'Érzékeny, gyulladt vagy pattanásos bőrre - bőrnyugtatás, gyulladáscsökkentés',
                'rental_id' => null,
            ],
            [
                'name' => 'Hydroglow sensitive arc + dekoltázs',
                'category' => 'Gépi kezelések',
                'duration' => '~90 perc',
                'price' => 9000,
                'features' => 'letisztítás, hidroabrázió, tonizálás, kímélő arcmasszázs, hidegkalapács, bőrnyugtató / gyulladáscsökkentő
arcpakolás, oxigénpisztoly',
                'other_features' => 'Érzékeny, gyulladt vagy pattanásos bőrre - bőrnyugtatás, gyulladáscsökkentés',
                'rental_id' => null,
            ],
            //Smink
            [
                'name' => 'Nappali',
                'category' => 'Smink',
                'duration' => null,
                'price' => 6000,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Alkalmi',
                'category' => 'Smink',
                'duration' => null,
                'price' => 7500,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Alkalmi',
                'category' => 'Smink',
                'duration' => null,
                'price' => 9000,
                'features' => 'műszempillával',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Menyasszonyi',
                'category' => 'Smink',
                'duration' => null,
                'price' => 20000,
                'features' => 'próbasminkkel',
                'other_features' => null,
                'rental_id' => null,
            ],
            //Szempilla/Szemöldök
            [
                'name' => 'Szempillafestés',
                'category' => 'Szempilla/Szemöldök',
                'duration' => null,
                'price' => 1700,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Szemöldökfestés',
                'category' => 'Szempilla/Szemöldök',
                'duration' => null,
                'price' => 1400,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Szemöldökigazítás',
                'category' => 'Szempilla/Szemöldök',
                'duration' => null,
                'price' => 1300,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Szemöldökigazítás + festés',
                'category' => 'Szempilla/Szemöldök',
                'duration' => null,
                'price' => 2700,
                'features' => '',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Szemöldök- és szempillafestés + szemöldökigazítás',
                'category' => 'Szempilla/Szemöldök',
                'duration' => null,
                'price' => 4400,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Szempilla lifting',
                'category' => 'Szempilla/Szemöldök',
                'duration' => null,
                'price' => 7000,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Szempilla lifting festéssel',
                'category' => 'Szempilla/Szemöldök',
                'duration' => null,
                'price' => 8000,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            //Gyanta
            [
                'name' => 'Láb térdig',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 3600,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Comb',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 3600,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Láb végig',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 5000,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Hónalj',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 1800,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Kar könyékig',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 2000,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Kar végig',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 2500,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Bajusz',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 1300,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Áll',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 1400,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Szemöldök',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 1300,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Bikini Vonal',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 2000,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Intim',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 4500,
                'features' => 'csak elől',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Teljes intim',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => 5000,
                'features' => 'Brazil',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Fenék',
                'category' => 'Gyanta',
                'duration' => null,
                'price' => '500/1000',
                'features' => 'Ánusz/Teljes',
                'other_features' => null,
                'rental_id' => null,
            ],
            //Sminktetoválás
            [
                'name' => 'Ombre Szemöldöktetoválás',
                'category' => 'Sminktetoválás',
                'duration' => null,
                'price' => 60000 ,
                'features' => 'púderes, porhatású',
                'other_features' => null,
                'rental_id' => null,
            ],
            [
                'name' => 'Hairstroke Szemöldöktetoválás',
                'category' => 'Sminktetoválás',
                'duration' => null,
                'price' => 60000,
                'features' => null,
                'other_features' => null,
                'rental_id' => null,
            ],
        ]);
    }
}
